// Runner dei test del motore IBD — nessun framework.
// Esecuzione:  node tests/run.mjs   (oppure: npm test)   Exit code 0 = tutto verde.
//
// Perche' esistono: fino alla v3.1.7 la logica viveva dentro index.html e non era
// eseguibile fuori dal browser. La tabella qui sotto — una metaplasia di Paneth
// "fortemente suggestiva" per RCU e una RCU conclamata solo "compatibile" — e' il tipo
// di cosa che una suite sbatte in faccia al primo `npm test`.
import { createRequire } from 'node:module';
import fs from 'node:fs';
const require = createRequire(import.meta.url);
const E = require('../engine.js');

let pass = 0, fail = 0; const failures = [];
const check = (n, c, d = '') => c ? pass++ : (fail++, failures.push(n + (d ? ` — ${d}` : '')));
const eq = (n, a, b) => check(n, a === b, `atteso ${JSON.stringify(b)}, ottenuto ${JSON.stringify(a)}`);
const section = t => console.log(`\n• ${t}`);

const C = o => Object.assign({ granulomi_epitelioidi:'assente', neutrofili_epitelio:'assente',
  neutrofili_lamina_propria:'assente', ascessi_criptici:'assente', plasmacellule_basale:'assente',
  distorsione_architettura:'assente', metaplasia_paneth:'assente', ulcerazione:'assente',
  fibrosi_sottomucosa:'assente', displasia:'assente' }, o);
const I = o => Object.assign({ granulomi_epitelioidi:'assente', neutrofili_lamina_propria:'assente',
  erosioni_ulcerazioni:'assente', iperplasia_linfoide:'assente', edema_lamina_propria:'assente',
  atrofia_villi:'assente', plasmacellule_aumentate:'assente', fibrosi_sottomucosa:'assente' }, o);
const col = (site, f) => ({ site, siteType:'colon', findings: C(f) });
const ile = f => ({ site:'ileo', siteType:'ileum', findings: I(f) });
const UC = f => Object.assign({ neutrofili_epitelio:'marcata', ascessi_criptici:'presente',
  plasmacellule_basale:'presente', distorsione_architettura:'presente' }, f || {});

const st = (specimens, over = {}) => Object.assign({
  specimens,
  ihcData: { cd68_pattern:'non_eseguito', p53_pattern:'non_eseguito', cmv_status:'non_eseguito' },
  ibdNota: { enabled:false, diagnosiIniziale:null, diagnosiAttuale:null, therapyOngoing:false },
  altreColiti: { banda_collagene:'assente', banda_collagene_um:null, iel_aumentati:'assente',
    iel_count:null, pattern_superficiale:false, architettura_conservata:false, atrofia_ischemica:false,
    membrane_ialine:false, emorragia_recente:false, apoptosi_cripte:'assente', ulcere_diaframma:false },
  diagnosiVeloce: { selected:null, testo:null, gradoManuale:null, autoGenerated:false }
}, over);
const interpret = s => E.interpretScoringGraduated(s, E.calculateScoring(s));
const nancyOf = s => E.calculateNancyIndex(s);

// ══════════════════════════════════════════════════════════════════════════
section('evidenza e separazione (v3.2.0)');
{
  const s1 = st([col('sigma', { metaplasia_paneth:'presente' })]);
  const sc1 = E.calculateScoring(s1);
  eq('una sola voce → punteggio grezzo uc 15', sc1.rawScores.uc, 15);
  eq('normalizzato resta 100 (e non deve piu contare)', sc1.scores.uc, 100);
  eq('evidenza sotto la soglia minima', sc1.evidence.aboveFloor, false);
  eq('un reperto contato', sc1.evidence.nFindings, 1);

  const s2 = st(['retto','sigma','discendente','trasverso'].map(x => col(x, UC())));
  const sc2 = E.calculateScoring(s2);
  eq('RCU 4 sedi → evidenza solida', sc2.evidence.level, 'solida');
  eq('RCU 4 sedi → separazione netta', sc2.separation.level, 'netta');
  check('RCU 4 sedi → grezzi molto maggiori', sc2.rawScores.uc > 400, String(sc2.rawScores.uc));

  eq('separazione: 100 vs 0 → netta', E.assessSeparation({ crohn:100, uc:0 }).level, 'netta');
  eq('separazione: 100 vs 90 → ambigua', E.assessSeparation({ crohn:100, uc:90 }).level, 'ambigua');
  eq('separazione: 100 vs 70 → moderata', E.assessSeparation({ crohn:100, uc:70 }).level, 'moderata');
  eq('separazione: 0 vs 0 → ambigua', E.assessSeparation({ crohn:0, uc:0 }).level, 'ambigua');
  eq('gradeConfidence: solida+netta → alta', E.gradeConfidence({ level:'solida' }, { level:'netta' }), 'alta');
  eq('gradeConfidence: moderata+netta → probabile', E.gradeConfidence({ level:'moderata' }, { level:'netta' }), 'probabile');
  eq('gradeConfidence: insufficiente → suggestivo', E.gradeConfidence({ level:'insufficiente' }, { level:'netta' }), 'suggestivo');
}

section('la tabella che ha motivato la riscrittura');
{
  const paneth = interpret(st([col('sigma', { metaplasia_paneth:'presente' })]));
  eq('metaplasia di Paneth isolata → aspecifico', paneth.level, 'insufficiente');
  check('non nomina la RCU', !/ulcerosa/i.test(paneth.headline), paneth.headline);

  const gran = interpret(st([col('sigma', { granulomi_epitelioidi:'presente' })]));
  eq('un granuloma isolato → suggestivo, non "alta"', gran.level, 'suggestivo');
  check('nomina il Crohn con cautela', /suggestivo ma non diagnostico/i.test(gran.headline), gran.headline);

  const rcu = interpret(st(['retto','sigma','discendente','trasverso'].map(x => col(x, UC()))));
  eq('RCU conclamata 4 sedi → alta', rcu.level, 'alta');
  check('nomina la rettocolite ulcerosa', /ulcerosa/i.test(rcu.headline), rcu.headline);

  const abscess = interpret(st([col('retto', { ascessi_criptici:'presente' })]));
  eq('ascessi criptici isolati → aspecifico', abscess.level, 'insufficiente');

  const ulc = interpret(st([col('retto', { ulcerazione:'presente' })]));
  eq('una sola ulcerazione non fa il Crohn', ulc.level, 'insufficiente');

  const fib = interpret(st([col('sigma', { fibrosi_sottomucosa:'lieve' })]));
  eq('fibrosi lieve isolata → aspecifico (non IBDU)', fib.level, 'insufficiente');
}

section('Crohn: senza granulomi non si arriva ad "alta"');
{
  const conGran = interpret(st([
    ile({ granulomi_epitelioidi:'presente', erosioni_ulcerazioni:'presente', atrofia_villi:'marcata', plasmacellule_aumentate:'presente' }),
    col('cieco', { granulomi_epitelioidi:'presente', neutrofili_epitelio:'moderata' })]));
  eq('Crohn con granulomi → alta', conGran.level, 'alta');

  const senzaGran = interpret(st([
    ile({ erosioni_ulcerazioni:'presente', atrofia_villi:'marcata', iperplasia_linfoide:'presente', plasmacellule_aumentate:'presente' }),
    col('cieco', { neutrofili_epitelio:'moderata', distorsione_architettura:'presente' })]));
  eq('Crohn senza granulomi → al massimo probabile', senzaGran.level, 'probabile');
  check('nota epistemica sulla transmuralita', /transmuralità/i.test(senzaGran.epistemicNote || ''), senzaGran.epistemicNote);
}

section('IBDU dalla contraddizione, non dalla vicinanza fra percentuali');
{
  const contr = interpret(st([col('sigma', { granulomi_epitelioidi:'presente' }), col('retto', UC())]));
  eq('granulomi + cronicita RCU → IBDU', contr.primary, 'IBDU');
  check('motivata dalla contraddizione', /contraddittorio/i.test(contr.description), contr.description);

  const skip = interpret(st([col('retto', {}), col('sigma', UC()), col('discendente', {}), col('trasverso', UC())]));
  eq('skip lesions + cronicita RCU → IBDU', skip.primary, 'IBDU');
}

section('Nancy Index');
{
  const rcuNota = { ibdNota: { enabled:true, diagnosiIniziale:'RCU', diagnosiAttuale:'RCU', therapyOngoing:false } };
  const n = f => nancyOf(st([col('retto', f)], rcuNota));
  eq('ascessi criptici da soli → grado 3', n({ ascessi_criptici:'presente' }).score, 3);
  eq('ulcerazione → grado 4', n({ ulcerazione:'presente' }).score, 4);
  eq('neutrofili epitelio lievi → grado 2', n({ neutrofili_epitelio:'lieve' }).score, 2);
  eq('neutrofili lamina propria moderati → grado 3', n({ neutrofili_lamina_propria:'moderata' }).score, 3);
  eq('neutrofili lamina propria lievi → grado 2', n({ neutrofili_lamina_propria:'lieve' }).score, 2);
  eq('sola cronicita → grado 1', n({ plasmacellule_basale:'presente' }).score, 1);
  eq('mucosa muta → grado 0', n({}).score, 0);
  check('nota metodologica sui proxy', /infiltrato cronico/i.test(n({}).proxyNote || ''));
  eq('non applicabile senza RCU nota', nancyOf(st([col('retto', { ulcerazione:'presente' })])).applicable, false);
  // vecchio caso salvato, senza il campo neutrofili_lamina_propria
  const legacy = { site:'retto', siteType:'colon', findings: { granulomi_epitelioidi:'assente', neutrofili_epitelio:'assente',
    ascessi_criptici:'assente', plasmacellule_basale:'assente', distorsione_architettura:'assente',
    metaplasia_paneth:'assente', ulcerazione:'assente', fibrosi_sottomucosa:'assente', displasia:'assente' } };
  eq('caso legacy senza il nuovo campo → grado 0', nancyOf(st([legacy], rcuNota)).score, 0);
  check('caso legacy non risulta alterato', E.isMorphologicallyNormal(st([legacy])));
}

section('altre coliti e IBD coesistono');
{
  const s = st([ile({ granulomi_epitelioidi:'presente', erosioni_ulcerazioni:'presente', atrofia_villi:'marcata' })],
    { altreColiti: Object.assign(st([]).altreColiti, { banda_collagene:'ispessita', banda_collagene_um:14 }) });
  const r = interpret(s);
  eq('la diagnosi principale resta la collagenosica', r.primary, 'Colite Collagenosica');
  check('il Crohn non viene piu scartato', !!r.concurrent, JSON.stringify(r.concurrent));
  check('il concomitante nomina il Crohn', /Crohn/.test(r.concurrent.headline), r.concurrent.headline);
  check('nota sulla sovrapposizione', /sovrapporsi/i.test(r.epistemicNote || ''));

  const pura = interpret(st([col('sigma', {})],
    { altreColiti: Object.assign(st([]).altreColiti, { banda_collagene:'ispessita' }) }));
  eq('collagenosica pura resta senza concomitante', pura.concurrent, null);
}

section('normalita, IHC e assenza di campioni');
{
  eq('nessun campione ≠ mucosa normale', interpret(st([])).level, 'nessun-campione');
  eq('tre sedi mute → normale', interpret(st(['retto','sigma','cieco'].map(x => col(x, {})))).level, 'normale');

  const cmv = interpret(st([col('sigma', {})], { ihcData: { cd68_pattern:'non_eseguito', p53_pattern:'non_eseguito', cmv_status:'positivo' } }));
  check('CMV positivo non esce come "nella norma"', !/nella norma/i.test(cmv.headline), cmv.headline);
  check('CMV citato nella descrizione', /CMV/.test(cmv.description), cmv.description);

  const cd68 = interpret(st([col('sigma', {})], { ihcData: { cd68_pattern:'aggregati_profondi', p53_pattern:'non_eseguito', cmv_status:'non_eseguito' } }));
  check('CD68 profondo non esce come "nella norma"', !/nella norma/i.test(cd68.headline), cd68.headline);

  // il nuovo campo colon entra nel giudizio di normalita
  check('neutrofili LP nel colon impediscono "normale"',
    !E.isMorphologicallyNormal(st([col('sigma', { neutrofili_lamina_propria:'lieve' })])));
}

section('pattern topografico');
{
  const uno = E.analyzeTopographicPattern(st([col('retto', UC()), col('sigma', {})]));
  eq('una sola sede coinvolta → continuita non valutabile', uno.continuity, 'non valutabile (meno di due sedi coinvolte)');

  const due = E.analyzeTopographicPattern(st([col('retto', UC()), col('sigma', UC())]));
  eq('due sedi contigue → continua', due.continuity, 'continua');

  // Primo gap NON campionato (manca l'ascendente fra cieco e trasverso), secondo gap
  // con entrambe le sedi intermedie campionate (discendente e sigma fra trasverso e retto):
  // prima si usciva al primo gap e l'esito restava "indeterminabile".
  const misto = E.analyzeTopographicPattern(st([
    col('cieco', UC()), col('trasverso', UC()), col('discendente', {}), col('sigma', {}), col('retto', UC())]));
  check('skip lesion riconosciuta oltre il primo gap', misto.skipLesions === true,
    JSON.stringify({ skip: misto.skipLesions, ind: misto.skipLesionsIndeterminate }));
}

section('estensione RCU e descrizione microscopica (v3.3.0)');
{
  // retto + sigma coinvolti e nient'altro campionato: "sinistra" non e' dimostrabile
  const dueSedi = interpret(st(['retto','sigma'].map(x => col(x, UC()))));
  check('retto+sigma soli → non "sinistra"', !/sinistra/i.test(dueSedi.headline), dueSedi.headline);
  const conTrasverso = interpret(st([col('retto', UC()), col('sigma', UC()), col('discendente', UC()), col('trasverso', {})]));
  check('trasverso campionato indenne → "sinistra"', /sinistra/i.test(conTrasverso.headline), conTrasverso.headline);
  const soloRetto = interpret(st([col('retto', UC())]));
  check('solo retto campionato → non "proctite"', !/proctite/i.test(soloRetto.headline), soloRetto.headline);

  const d = E.describeSpecimenMorphology(col('sigma', UC()));
  check('RCU attiva → colite cronica attiva moderata', /colite cronica attiva \(attività moderata\)/.test(d), d);
  check('elenca la plasmocitosi basale', /plasmocitosi basale/.test(d), d);
  check('elenca gli ascessi criptici', /ascessi criptici/.test(d), d);
  const q = E.describeSpecimenMorphology(col('retto', { distorsione_architettura:'presente' }));
  check('sola cronicita → quiescente', /quiescente/.test(q), q);
  const sev = E.describeSpecimenMorphology(col('retto', UC({ ulcerazione:'presente' })));
  check('ulcerazione → attivita severa', /attività severa/.test(sev), sev);
  const pan = E.describeSpecimenMorphology(col('cieco', { metaplasia_paneth:'presente' }));
  check('Paneth nel cieco non e metaplasia', !/metaplasia/.test(pan), pan);
  check('mucosa muta → conservata', /conservata/.test(E.describeSpecimenMorphology(col('sigma', {}))));
  check('ileo attivo', /ileite/.test(E.describeSpecimenMorphology(ile({ erosioni_ulcerazioni:'presente' }))));

  const neg = E.describeCaseNegatives(st(['retto','sigma'].map(x => col(x, UC()))));
  check('negativi: granulomi', neg.some(x => /granulomi/.test(x)), JSON.stringify(neg));
  check('negativi: displasia', neg.some(x => /displasia/.test(x)), JSON.stringify(neg));
  const distr = E.describeDistribution(st(['retto','sigma'].map(x => col(x, UC()))));
  check('distribuzione: continua, retto coinvolto', /continua/.test(distr) && /retto coinvolto/.test(distr), distr);
  check('distribuzione: estensione non definibile', /non definibile/.test(distr), distr);
}

section('purezza e forma');
{
  const s = st([col('sigma', UC())]);
  const snap = JSON.stringify(s);
  E.interpretScoringGraduated(s, E.calculateScoring(s));
  E.detectContradictoryPatterns(s, E.calculateScoring(s));
  E.analyzeTopographicPattern(s);
  eq('il motore non muta lo stato', JSON.stringify(s), snap);
  const sc = E.calculateScoring(s);
  check('scoring espone ibduRaw', typeof sc.ibduRaw === 'number');
  check('scoring espone evidenza e separazione', !!sc.evidence && !!sc.separation);
}

section('coerenza versione e confini del motore');
{
  const pkg = JSON.parse(fs.readFileSync(new URL('../package.json', import.meta.url), 'utf8'));
  const html = fs.readFileSync(new URL('../index.html', import.meta.url), 'utf8');
  const eng = fs.readFileSync(new URL('../engine.js', import.meta.url), 'utf8');
  check('titolo allineato a package.json', html.includes(`IBD Diagnostic Tool v${pkg.version}`), pkg.version);
  check('APP_VERSION allineata', html.includes(`const APP_VERSION = '${pkg.version}'`));
  check('engine.js caricato con ?v= della versione', html.includes(`engine.js?v=${pkg.version}`));
  check('il motore non tocca il DOM', !/document\.|getElementById|window\./.test(eng));
}

console.log(`\n${fail === 0 ? 'OK' : 'FALLITO'} — ${pass} pass, ${fail} fail`);
if (failures.length) { console.log('\nFallimenti:'); failures.forEach(f => console.log('  ✗ ' + f)); }
process.exit(fail === 0 ? 0 : 1);
